
jobs:
  include:
      os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"

cache:
  yarn: true
  directories:
    - node_modules
    - /usr/local/opt/llvm

before_install: git pull

script:
  - npm test
